-- MySQL Script generated by MySQL Workbench
-- Tue Aug 28 20:45:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_mais_vida
-- -----------------------------------------------------
-- Banco de dados referente ao processo seletivo, mais vida.

-- -----------------------------------------------------
-- Schema db_mais_vida
--
-- Banco de dados referente ao processo seletivo, mais vida.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mais_vida` DEFAULT CHARACTER SET utf8 ;
USE `db_mais_vida` ;

-- -----------------------------------------------------
-- Table `db_mais_vida`.`tb_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mais_vida`.`tb_estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `no_estado` VARCHAR(45) NULL,
  `sg_estado` VARCHAR(2) NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mais_vida`.`tb_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mais_vida`.`tb_pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT COMMENT 'identificador da pessoa',
  `no_pessoa` VARCHAR(200) NOT NULL COMMENT 'Nome da pessoa',
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_pessoa`),
  INDEX `idx_fk_pessoa_estado` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `db_mais_vida`.`tb_estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mais_vida`.`tb_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mais_vida`.`tb_documento` (
  `id_documento` INT NOT NULL AUTO_INCREMENT COMMENT 'identificador do documento',
  `no_numero` VARCHAR(45) NULL,
  `no_tipo` VARCHAR(200) NULL,
  `id_pessoa` INT NOT NULL COMMENT 'identificador associativo a tabela pessoa',
  PRIMARY KEY (`id_documento`, `id_pessoa`),
  INDEX `idx_fk_doc_pessoa` (`id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_doc_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `db_mais_vida`.`tb_pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('AC', 'Acre');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('AL', 'Alagoas');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('AM', 'Amazonas');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('AP', 'Amapá');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('BA', 'Bahia');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('CE', 'Ceará');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('DF', 'Distrito Federal');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('ES', 'Espírito Santo');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('GO', 'Goiás');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('MA', 'Maranhão');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('MG', 'Minas Gerais');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('MS', 'Mato Grosso do Sul');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('MT', 'Mato Grosso');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('PA', 'Pará');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('PB', 'Paraíba');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('PE', 'Pernambuco');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('PI', 'Piauí');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('PR', 'Paraná');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('RJ', 'Rio de Janeiro');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('RN', 'Rio Grande do Norte');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('RO', 'Rondônia');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('RR', 'Roraima');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('RS', 'Rio Grande do Sul');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('SC', 'Santa Catarina');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('SE', 'Sergipe');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('SP', 'São Paulo');
INSERT INTO db_mais_vida.tb_estado (sg_estado, no_estado) VALUES ('TO', 'Tocantins');